### Import the saved model and check performance with sample data

In [1]:
import pickle
import pandas as pd
import numpy as np

In [3]:
with open('data\\external\\XGBClassifier_model.pkl', 'rb') as file:
    trained_model = pickle.load(file)

In [12]:
dataset = pd.read_csv('data\\processed\\processed_data.csv')

In [13]:
sample_size = 25 

random_sample = dataset.sample(n=sample_size, random_state=42)  

random_sample

,Age,EducationBackground,MaritalStatus,EmpDepartment,EmpJobRole,BusinessTravelFrequency,DistanceFromHome,EmpEducationLevel,EmpEnvironmentSatisfaction,EmpHourlyRate,...,EmpRelationshipSatisfaction,TotalWorkExperienceInYears,TrainingTimesLastYear,EmpWorkLifeBalance,ExperienceYearsAtThisCompany,ExperienceYearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Attrition,PerformanceRating
1178,22,2,1,2,2,1,6,1,1,69,...,4,3.0,3,3,2.0,2.0,2.0,2.0,1,3
865,31,1,1,1,1,1,6,4,2,76,...,2,12.0,3,2,7.0,7.0,7.0,7.0,2,2
101,39,1,1,4,10,1,2,3,4,42,...,3,13.0,2,3,5.0,4.0,0.0,4.0,1,3
439,29,1,1,3,6,2,2,1,4,97,...,3,4.0,3,3,3.0,2.0,0.0,2.0,1,3
58,36,6,1,4,10,1,13,3,3,36,...,2,8.0,2,3,5.0,2.0,0.0,4.0,1,3
1120,35,1,2,2,2,1,22,3,4,46,...,3,6.0,2,3,5.0,4.0,4.0,3.0,1,3
323,51,2,2,3,6,2,6,2,2,40,...,2,8.0,6,2,7.0,0.0,7.0,7.0,1,3
974,42,1,2,2,2,1,17,2,4,82,...,3,10.0,1,3,3.0,2.0,0.0,2.0,1,3
411,34,4,1,4,10,1,9,4,1,52,...,4,2.0,0,3,2.0,2.0,2.0,2.0,2,2
855,34,1,2,2,2,2,7,3,1,66,...,4,9.0,3,3,9.0,7.0,0.0,6.0,2,4
820,45,1,3,2,16,1,7,3,2,59,...,3,25.0,2,3,1.0,0.0,0.0,0.0,1,3
44,40,2,1,2,2,2,2,2,3,38,...,4,8.0,2,3,8.0,7.0,3.0,7.0,1,4
49,29,1,1,2,2,1,1,2,2,36,...,4,1.0,1,3,1.0,0.0,0.0,0.0,2,3
849,34,5,2,2,2,1,6,4,1,41,...,3,16.0,3,3,16.0,13.0,2.0,10.0,1,3
240,29,2,1,3,12,1,8,1,2,79,...,3,10.0,2,2,10.0,7.0,1.0,2.0,1,2
170,35,5,3,3,6,1,10,3,2,45,...,1,3.0,4,2,3.0,2.0,1.0,2.0,1,2
523,34,1,3,5,9,1,3,3,4,66,...,3,11.0,2,3,11.0,8.0,7.0,9.0,1,3
765,41,1,2,1,1,1,1,2,2,94,...,1,8.0,0,1,6.0,4.0,0.0,5.0,2,2
838,40,1,1,2,2,2,1,4,3,78,...,4,22.0,3,2,22.0,3.0,1.0,11.0,1,4
423,57,1,1,3,4,1,1,2,2,93,...,1,13.0,2,2,12.0,9.0,2.0,8.0,1,2
380,26,2,2,3,4,1,2,1,1,36,...,4,5.0,2,3,4.0,3.0,1.0,1.0,1,3
609,34,1,1,3,6,2,9,4,4,93,...,3,11.0,3,2,7.0,1.0,0.0,7.0,2,3
676,56,3,1,1,1,1,11,5,4,89,...,3,6.0,3,3,0.0,0.0,0.0,0.0,1,3
344,34,1,3,3,13,1,9,3,4,86,...,4,10.0,0,2,9.0,7.0,1.0,6.0,1,3
109,47,1,2,1,5,1,2,4,4,65,...,1,3.0,3,2,3.0,2.0,1.0,2.0,1,3

In [14]:
X = random_sample.drop(columns=['PerformanceRating'],axis=1)

In [15]:
trained_model.predict(X)

array([1, 0, 1, 1, 1, 1, 1, 1, 0, 2, 1, 2, 1, 1, 0, 0, 1, 1, 2, 0, 0, 1,
       1, 1, 1], dtype=int64)

In [16]:
y = random_sample['PerformanceRating']
class_mapping = {label: idx for idx, label in enumerate(np.unique(y))}
y_mapped = np.vectorize(class_mapping.get)(y)
y_mapped

array([1, 0, 1, 1, 1, 1, 1, 1, 0, 2, 1, 2, 1, 1, 0, 0, 1, 0, 2, 0, 1, 1,
       1, 1, 1])

Saved saveral models.
* When `XGBClassifier` and `Random Forest` is used, it's predicting almost all of the values correctly.
* `AdaBoost` predictions are little less accurate.